import { randomUUID } from "crypto";
import type { WarEvent, NewsItem, Alert } from "@shared/schema";
import { storage } from "./storage";

export async function seedIfEmpty(): Promise<void> {
  const seeded = await storage.isSeeded();
  if (seeded) {
    console.log("[seed] Database already has data, skipping seed");
    return;
  }

  console.log("[seed] Seeding database with initial data...");

  const now = new Date();
  const minutesAgo = (m: number) => new Date(now.getTime() - m * 60000).toISOString();

  const events: WarEvent[] = [
    {
      id: randomUUID(),
      type: "missile_launch",
      title: "Ballistic missile launched from southern Iran",
      description: "Medium-range ballistic missile detected launching from launch site near Shiraz heading northwest",
      location: "Shiraz, Iran",
      lat: 29.5918,
      lng: 52.5836,
      country: "Iran",
      source: "Satellite Detection",
      timestamp: minutesAgo(3),
      threatLevel: "critical",
      verified: true,
    },
    {
      id: randomUUID(),
      type: "missile_intercept",
      title: "Arrow-3 successful interception over Jordan",
      description: "Israeli Arrow-3 system intercepted incoming ballistic missile at high altitude over Jordanian airspace",
      location: "Jordanian Airspace",
      lat: 31.9,
      lng: 36.0,
      country: "Jordan",
      source: "IDF Spokesperson",
      timestamp: minutesAgo(2),
      threatLevel: "high",
      verified: true,
    },
    {
      id: randomUUID(),
      type: "drone_launch",
      title: "Multiple drone swarm detected from Iraq",
      description: "Cluster of 15+ UAVs detected launching from militia-controlled area in western Iraq",
      location: "Al-Qa'im, Iraq",
      lat: 34.3767,
      lng: 41.0744,
      country: "Iraq",
      source: "Radar Detection",
      timestamp: minutesAgo(8),
      threatLevel: "high",
      verified: true,
    },
    {
      id: randomUUID(),
      type: "missile_launch",
      title: "Cruise missiles launched from Yemen",
      description: "Houthi forces launched 3 cruise missiles toward Eilat from Sanaa region",
      location: "Sanaa, Yemen",
      lat: 15.3694,
      lng: 44.191,
      country: "Yemen",
      source: "CENTCOM",
      timestamp: minutesAgo(12),
      threatLevel: "critical",
      verified: true,
    },
    {
      id: randomUUID(),
      type: "missile_intercept",
      title: "Iron Dome intercepts rockets from Gaza",
      description: "Iron Dome system successfully intercepted 8 out of 10 rockets launched from northern Gaza Strip",
      location: "Sderot, Israel",
      lat: 31.5246,
      lng: 34.5968,
      country: "Israel",
      source: "IDF Spokesperson",
      timestamp: minutesAgo(5),
      threatLevel: "high",
      verified: true,
    },
    {
      id: randomUUID(),
      type: "air_raid_alert",
      title: "Red Alert - Tel Aviv metropolitan area",
      description: "Sirens sounding in Tel Aviv and surrounding areas. Residents instructed to enter shelters",
      location: "Tel Aviv, Israel",
      lat: 32.0853,
      lng: 34.7818,
      country: "Israel",
      source: "Pikud HaOref",
      timestamp: minutesAgo(1),
      threatLevel: "critical",
      verified: true,
    },
    {
      id: randomUUID(),
      type: "missile_launch",
      title: "Rockets fired from southern Lebanon",
      description: "Hezbollah launched approximately 20 rockets toward northern Israel from Tyre area",
      location: "Tyre, Lebanon",
      lat: 33.2705,
      lng: 35.1966,
      country: "Lebanon",
      source: "UNIFIL",
      timestamp: minutesAgo(15),
      threatLevel: "high",
      verified: true,
    },
    {
      id: randomUUID(),
      type: "missile_intercept",
      title: "David's Sling intercepts medium-range missile",
      description: "David's Sling system intercepted medium-range rocket over Haifa Bay area",
      location: "Haifa, Israel",
      lat: 32.7940,
      lng: 34.9896,
      country: "Israel",
      source: "IDF Spokesperson",
      timestamp: minutesAgo(14),
      threatLevel: "medium",
      verified: true,
    },
    {
      id: randomUUID(),
      type: "explosion",
      title: "Explosion reported near Damascus International Airport",
      description: "Large explosion reported near Damascus International Airport. Cause under investigation",
      location: "Damascus, Syria",
      lat: 33.4114,
      lng: 36.5153,
      country: "Syria",
      source: "SOHR",
      timestamp: minutesAgo(22),
      threatLevel: "medium",
      verified: false,
    },
    {
      id: randomUUID(),
      type: "drone_intercept",
      title: "US Navy shoots down drone over Red Sea",
      description: "USS Carney destroyer intercepted armed drone approaching coalition shipping in Red Sea",
      location: "Red Sea",
      lat: 15.5,
      lng: 41.0,
      country: "International Waters",
      source: "CENTCOM",
      timestamp: minutesAgo(30),
      threatLevel: "medium",
      verified: true,
    },
    {
      id: randomUUID(),
      type: "military_operation",
      title: "IDF ground operation in Rafah continues",
      description: "Israeli forces conducting targeted operations in eastern Rafah, multiple engagements reported",
      location: "Rafah, Gaza",
      lat: 31.2850,
      lng: 34.2447,
      country: "Palestine",
      source: "IDF Spokesperson",
      timestamp: minutesAgo(45),
      threatLevel: "high",
      verified: true,
    },
    {
      id: randomUUID(),
      type: "missile_launch",
      title: "Anti-ship missile launched toward Strait of Hormuz",
      description: "IRGC Navy launched anti-ship missile during exercises near Strait of Hormuz",
      location: "Strait of Hormuz",
      lat: 26.5667,
      lng: 56.25,
      country: "Iran",
      source: "OSINT",
      timestamp: minutesAgo(60),
      threatLevel: "medium",
      verified: false,
    },
    {
      id: randomUUID(),
      type: "sirens",
      title: "Sirens activated in Kiryat Shmona",
      description: "Sirens activated in Kiryat Shmona and surrounding communities in Upper Galilee",
      location: "Kiryat Shmona, Israel",
      lat: 33.2073,
      lng: 35.5707,
      country: "Israel",
      source: "Pikud HaOref",
      timestamp: minutesAgo(7),
      threatLevel: "critical",
      verified: true,
    },
    {
      id: randomUUID(),
      type: "missile_hit",
      title: "Rocket impact in open area near Ashkelon",
      description: "One rocket impact reported in open area near Ashkelon. No casualties reported",
      location: "Ashkelon, Israel",
      lat: 31.6688,
      lng: 34.5743,
      country: "Israel",
      source: "Israel Police",
      timestamp: minutesAgo(4),
      threatLevel: "high",
      verified: true,
    },
    {
      id: randomUUID(),
      type: "drone_launch",
      title: "Reconnaissance drone spotted over Golan Heights",
      description: "Unidentified reconnaissance UAV detected flying over northern Golan Heights from Syria",
      location: "Golan Heights",
      lat: 33.1,
      lng: 35.8,
      country: "Israel",
      source: "IAF",
      timestamp: minutesAgo(18),
      threatLevel: "medium",
      verified: true,
    },
  ];

  const news: NewsItem[] = [
    { id: randomUUID(), title: "IDF confirms interception of multiple ballistic missiles from Iran in coordinated defense operation", source: "IDF Spokesperson", timestamp: minutesAgo(2), category: "Military", breaking: true },
    { id: randomUUID(), title: "UN Security Council emergency session called following escalation in Middle East", source: "Reuters", timestamp: minutesAgo(5), category: "Diplomacy", breaking: true },
    { id: randomUUID(), title: "US CENTCOM confirms joint interception operations with Israeli forces over Jordan", source: "Reuters", timestamp: minutesAgo(8), category: "Military", breaking: true },
    { id: randomUUID(), title: "Iron Dome intercepts rocket barrage aimed at central Israel, all threats neutralized", source: "Times of Israel", timestamp: minutesAgo(6), category: "Defense", breaking: false },
    { id: randomUUID(), title: "Hezbollah claims responsibility for rocket attacks on northern Israel settlements", source: "Al Jazeera", timestamp: minutesAgo(15), category: "Military", breaking: false },
    { id: randomUUID(), title: "Israeli Home Front Command updates shelter guidelines for greater Tel Aviv", source: "Kann News", timestamp: minutesAgo(10), category: "Civil Defense", breaking: false },
    { id: randomUUID(), title: "Houthi spokesperson claims new long-range missile capability targeting Israel", source: "Telegram", timestamp: minutesAgo(20), category: "Military", breaking: false },
    { id: randomUUID(), title: "IDF conducting precision strikes on Hezbollah positions in southern Lebanon", source: "Channel 12", timestamp: minutesAgo(25), category: "Military", breaking: false },
    { id: randomUUID(), title: "Ben Gurion Airport operations temporarily suspended due to security situation", source: "Ynet", timestamp: minutesAgo(12), category: "Infrastructure", breaking: true },
    { id: randomUUID(), title: "US deploys additional THAAD battery to support Israeli air defense", source: "Reuters", timestamp: minutesAgo(35), category: "Defense", breaking: false },
    { id: randomUUID(), title: "Multiple explosions reported in Damascus suburbs, possibly Israeli strikes", source: "Telegram", timestamp: minutesAgo(40), category: "Military", breaking: false },
    { id: randomUUID(), title: "Jordan closes airspace to all civilian traffic amid regional escalation", source: "Al Jazeera", timestamp: minutesAgo(18), category: "Aviation", breaking: false },
  ];

  const alertList: Alert[] = [
    { id: randomUUID(), area: "Tel Aviv - Gush Dan", threat: "Missile threat - enter shelters immediately", timestamp: minutesAgo(1), active: true, lat: 32.0853, lng: 34.7818 },
    { id: randomUUID(), area: "Kiryat Shmona - Upper Galilee", threat: "Hostile aircraft intrusion", timestamp: minutesAgo(7), active: true, lat: 33.2073, lng: 35.5707 },
    { id: randomUUID(), area: "Sderot - Western Negev", threat: "Rocket and missile fire", timestamp: minutesAgo(5), active: true, lat: 31.5246, lng: 34.5968 },
    { id: randomUUID(), area: "Ashkelon", threat: "Rocket and missile fire", timestamp: minutesAgo(30), active: false, lat: 31.6688, lng: 34.5743 },
    { id: randomUUID(), area: "Haifa Bay", threat: "Hostile aircraft intrusion", timestamp: minutesAgo(45), active: false, lat: 32.7940, lng: 34.9896 },
    { id: randomUUID(), area: "Eilat - Arava", threat: "Missile threat from Yemen", timestamp: minutesAgo(60), active: false, lat: 29.5577, lng: 34.9519 },
  ];

  await storage.addEvents(events);
  await storage.addNews(news);
  await storage.addAlerts(alertList);

  console.log(`[seed] Seeded ${events.length} events, ${news.length} news, ${alertList.length} alerts`);
}
